require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")
require("core.ui")

require("plugins.theme")
-- 插件
require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
require("plugins.lspkind")
require("plugins.rainbow")
require("plugins.blankline")
require("plugins.auto_save")
