--core
require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")
require("core.ui")
--theme
require("plugins.theme")
--plug
require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins.lspkind")
require("plugins.rainbow")
require("plugins.blankline")
require("plugins.auto_save")
--start pack
require("plugins.index")
require("plugins.dap.dap-init")
